(function(b){var d=b(window);b.fn.asynchImageLoader=b.fn.jail=function(a){a=b.extend({timeout:10,effect:!1,speed:400,selector:null,offset:0,event:"load+scroll",callback:jQuery.noop,callbackAfterEachImage:jQuery.noop,placeholder:!1,container:window},a);b.jail.initialStack=this;this.data("triggerEl",a.selector?b(a.selector):d);!1!==a.placeholder&&this.each(function(){b(this).attr("src",a.placeholder)});/^load/.test(a.event)?b.asynchImageLoader.later.call(this,a):b.asynchImageLoader.onEvent.call(this,
a,this);return this};b.asynchImageLoader=b.jail={_purgeStack:function(a){for(var b=0;b!==a.length;)a[b].getAttribute("data-href")?b++:a.splice(b,1)},_loadOnEvent:function(a){var c=b(this),e=a.data.options;a=a.data.images;b.asynchImageLoader._loadImage(e,c);c.unbind(e.event,b.asynchImageLoader._loadOnEvent);b.asynchImageLoader._purgeStack(a);e.callback&&(b.asynchImageLoader._purgeStack(b.jail.initialStack),b.asynchImageLoader._launchCallback(b.jail.initialStack,e))},_bufferedEventListener:function(a){var c=
a.data.images,e=a.data.options,d=c.data("triggerEl");clearTimeout(c.data("poller"));c.data("poller",setTimeout(function(){c.each(function(){b.asynchImageLoader._loadImageIfVisible(e,this,d)});b.asynchImageLoader._purgeStack(c);e.callback&&(b.asynchImageLoader._purgeStack(b.jail.initialStack),b.asynchImageLoader._launchCallback(b.jail.initialStack,e))},e.timeout))},onEvent:function(a,c){c=c||this;if("scroll"===a.event||a.selector){var e=c.data("triggerEl");0<c.length?(e.bind(a.event,{images:c,options:a},
b.asynchImageLoader._bufferedEventListener),("scroll"===a.event||!a.selector)&&d.resize({images:c,options:a},b.asynchImageLoader._bufferedEventListener)):e&&e.unbind(a.event,b.asynchImageLoader._bufferedEventListener)}else c.bind(a.event,{options:a,images:c},b.asynchImageLoader._loadOnEvent)},later:function(a){var c=this;"load"===a.event&&c.each(function(){b.asynchImageLoader._loadImageIfVisible(a,this,c.data("triggerEl"))});b.asynchImageLoader._purgeStack(c);b.asynchImageLoader._launchCallback(c,
a);setTimeout(function(){"load"===a.event?c.each(function(){b.asynchImageLoader._loadImage(a,b(this))}):c.each(function(){b.asynchImageLoader._loadImageIfVisible(a,this,c.data("triggerEl"))});b.asynchImageLoader._purgeStack(c);b.asynchImageLoader._launchCallback(c,a);"load+scroll"===a.event&&(a.event="scroll",b.asynchImageLoader.onEvent(a,c))},a.timeout)},_launchCallback:function(a,c){0===a.length&&!b.jail.isCallback&&(c.callback.call(this,c),b.jail.isCallback=!0)},_loadImageIfVisible:function(a,
c,e){c=b(c);e=/scroll/i.test(a.event)?e:d;b.asynchImageLoader._isInTheScreen(e,c,a.offset)&&b.asynchImageLoader._loadImage(a,c)},_isInTheScreen:function(a,b,e){var d=a[0]===window,f=d?{top:0,left:0}:a.offset(),h=f.top+(d?a.scrollTop():0),d=f.left+(d?a.scrollLeft():0),f=d+a.width();a=h+a.height();var g=b.offset(),i=b.width();b=b.height();return h-e<=g.top+b&&a+e>=g.top&&d-e<=g.left+i&&f+e>=g.left},_loadImage:function(a,b){b.hide();b.attr("src",b.attr("data-href"));b.removeAttr("data-href");if(a.effect)if(a.speed)b[a.effect](a.speed);
else b[a.effect]();else b.show();a.callbackAfterEachImage.call(this,b,a)}}})(jQuery);function changePanelImage(b){$("carousel #panel").fadeOut("fast",function(){$("carousel #panel").attr("src",b);$("carousel #panel").fadeIn("fast")})}
function onLoad(){$(".asyncImg").jail({callback:function(){$(".asyncImg").addClass("asyncImgLoaded").removeClass("asyncImg")}});$("carousel").ready(function(){function b(){var a=$(".dealImg.active").parent().position();600<=a.left?$("#thumbs .item").animate({left:"-\x3d"+105*d+"px"},500):0>a.left&&$("#thumbs .item").animate({left:"+\x3d"+105*d+"px"},500)}$("carousel .dealImg").first().addClass("active");$("carousel #panel").attr("src",$("carousel .dealImg").first().attr("data-href"));1==$("carousel #thumbs .dealImg").length?
($("carousel #thumbs .dealImg").each(function(){var a=$(this);a.attr("src",a.attr("data-thumb"));$(a).parent().hide()}),$("carousel #prev").hide(),$("carousel #next").hide(),$("#carrossel").css("height","380px")):1<$("carousel #thumbs .dealImg").length&&($("carousel #thumbs .dealImg").each(function(){var a=$(this);a.attr("src",a.attr("data-thumb"));a.css("cursor","pointer");a.click(function(){$("carousel .dealImg").removeClass("active");a.addClass("active");changePanelImage(a.attr("data-href"))})}),
$("carousel #prev").css("cursor","pointer"),$("carousel #next").css("cursor","pointer"),$("carousel #prevThumb").css("cursor","pointer"),$("carousel #nextThumb").css("cursor","pointer"),$("carousel #prevThumb").click(function(){moveThumbLeft()}),$("carousel #nextThumb").click(function(){moveThumbRight()}),$("carousel #prev").click(function(){var a=0;$("carousel .dealImg").each(function(b){$(this).hasClass("active")&&($(this).removeClass("active"),a=b)});var c=$("carousel .dealImg").get(a-1);null==
c?($("carousel .dealImg").last().addClass("active"),changePanelImage($("carousel .dealImg").last().attr("data-href"))):($(c).addClass("active"),changePanelImage($(c).attr("data-href")));b()}),$("carousel #next").click(function(){var a=0;$("carousel .dealImg").each(function(b){$(this).hasClass("active")&&($(this).removeClass("active"),a=b)});var c=$("carousel .dealImg").get(a+1);null==c?($("carousel .dealImg").first().addClass("active"),changePanelImage($("carousel .dealImg").first().attr("data-href"))):
($(c).addClass("active"),changePanelImage($(c).attr("data-href")));b()}));var d=0;6<=$("#thumbs .scroll .item").length&&($("carousel").append("\x3cdiv id\x3d'prevThumb' class\x3d'ga-click ga-data' data-ga-category\x3d'oferta' data-ga-subcategory\x3d'carrosel-de-imagem-navegar-thumb-anterior' data-value\x3d'ga-main-value'\x3e \x3c \x3c/div\x3e"),$("carousel").append("\x3cdiv id\x3d'nextThumb' class\x3d'ga-click ga-data' data-ga-category\x3d'oferta' data-ga-subcategory\x3d'carrosel-de-imagem-navegar-thumb-proximo' data-value\x3d'ga-main-value''\x3e \x3e \x3c/div\x3e"),
$(".scroll").css({width:"3000px",left:"33px"}),$("#tocenter").css({left:"0",width:"100%"}),d=$("#thumbs .scroll .item").length-6,$("#prevThumb").click(function(){0!=$("#thumbs .scroll .item:first-child").position().left&&$("#thumbs .item").animate({left:"+\x3d105px"},500)}),$("#nextThumb").click(function(){600<=$("#thumbs .scroll .item:last-child").position().left&&$("#thumbs .item").animate({left:"-\x3d105px"},500)}))});$("input[name\x3d'childRadio']").ready(function(){$("input[name\x3d'childRadio']").click(function(){carregaTaxaById(this)})});
!1==$("input[name\x3dchildRadio]").is(":checked")?$("input[name\x3dchildRadio]:eq(0)").click():carregaTaxaById("input[name\x3dchildRadio]:checked")}function carregaTaxaById(b){b="#dealTax_"+$(b).val();$("#taxDeal").html($(b).html())}function old(){1<$("#carrossel li").length&&($("#carrossel").addClass("caroselativo"),$("#carrossel").nivoSlider({effect:"boxRandom",animSpeed:500,pauseTime:5E3,startSlide:0,controlNavThumbs:!0,afterChange:ThumbVisivel}))}var timeNow;
function setTimer(){if(!(null==timeNow||"undefined"==timeNow))if(!(null==dealDateValidEnd||"undefined"==dealDateValidEnd)){var b=new Date(dealDateValidEnd),d=(new Date(timeNow)).getTime(),b=b.getTime(),a=Math.floor(Math.round(b-d)/1E3);0<a&&(timeNow+=1E3);a%=86400;d=0>=a?0:Math.floor(a/3600);a%=3600;b=0>=a?0:Math.floor(a/60);a%=60;a=0>=a?0:Math.floor(a/1);d=2>(d+"").length?"0"+d:d;b=2>(b+"").length?"0"+b:b;a=2>(a+"").length?"0"+a:a;$("#timeRemaining").html(d+":"+b+":"+a)}}
function setSold(){null==dealId||("undefined"==dealId||1>dealId)||$.post("/dyn/sold.do",{dealId:dealId},function(b){$("#dealQuantitySold").text(b)})}function setRemaining(){null==dealId||("undefined"==dealId||1>dealId)||$.post("/dyn/remaining.do",{dealId:dealId},function(b){$("#dealQuantitySold").text(b)})}
$("#timeRemaining").ready(function(){$.post("/dyn/time.do",function(b){timeNow=new Number(b);window.setInterval(setTimer,1E3)}).error(function(){timeNow=jQuery.now();window.setInterval(setTimer,1E3)})});$("#dealQuantitySold").ready(function(){reverseCount?(setRemaining(),1E3<soldTimeout&&window.setInterval(setRemaining,soldTimeout)):1E3<soldTimeout&&window.setInterval(setSold,soldTimeout)});var showMoreSelected=!1;
function showMore(b,d){!0==showMoreSelected?$("#boxMaisInfo").toggle():(""!=b&&$.get("/descImage.do",{img:b},function(a){$("#boxImagemMaisInfo").html(a)}),""!=d&&$.get("/descVideo.do",{video:d},function(a){$("#boxVideoMaisInfo").html(a)}),showMoreSelected=!0)}isMobile()&&$("carousel").ready(function(){$("carousel").find("a").attr("href","#")});