$(document).ready(function(){function q(a){a.hasClass("srfilterall")||a.closest("ul").find("li.srfilterall").find("label").removeClass("ativo").find('input[type\x3d"checkbox"]').removeAttr("checked");var b=!1;a.closest("ul").find("li").each(function(){$(this).find("label").hasClass("ativo")&&(b=!0)});b||a.closest("ul").find("li.srfilterall").find("label").addClass("ativo").find('input[type\x3d"checkbox"]').attr("checked",!0)}function r(a){var b=[];null==a?$(".srfilterall").closest("ul").siblings("ul").find("input:checkbox").each(function(){b.push($(this).attr("id"))}):
$(".srfilterall",a).closest("ul").siblings("ul").find("input:checkbox").each(function(){b.push($(this).attr("id"))});return b}function c(a){return $("input:checkbox[name\x3d"+a+"]:checked").map(function(){return this.value}).get().join(",")}function s(a){-1==a.index()&&(a=$(".totalHits"));$("html,body").animate({scrollTop:a.offset().top},"slow")}function i(a,b,e){if(a.length){var d=!1;e?$.each(a.split(","),function(a,e){var c=$("#all-"+b);c.closest("li").siblings().each(function(){var a=$(this).find('input[type\x3d"checkbox"]');
a.val()==e&&(d=!0,a.attr("checked",!0).closest("label").addClass("ativo"))});d&&c.removeAttr("checked").closest("label").removeClass("ativo")}):$.each(a.split(","),function(a,e){var c=$("#"+b+"-"+e);c.length&&(d=!0,c.attr("checked",!0).closest("label").addClass("ativo"));d&&c.closest("ul").find("li.srfilterall").find("label").removeClass("ativo").find('input[type\x3d"checkbox"]').removeAttr("checked")});d&&(a=$("#all-"+b),a.closest("li").siblings("li").show(),a.closest("ul").find("li.showmore").remove())}}
var g=1,j="relevancia";$(".resultado-busca").find("li:nth-child(1)").nextAll().hide();var f=$("#srquery"),h=f.data("monthstravelreservation");i(h,"monthsTravelReservation");h=f.data("departurecities");i(h,"departureCities",!0);$(document).on("click","a.request, li.request, input.request, li.srfilterall, input.srfilterall, a.#loadmore, li.srsort, a.pagination",function(a){var b=$(this);b.is("a, li")&&a.preventDefault();b.hasClass("srfilterall")&&((b.is("li")?b:b.closest("li")).nextAll().find("input").attr("checked",
!1).closest("label").removeClass("ativo"),b.find("label").addClass("ativo").find('input[type\x3d"checkbox"]').attr("checked",!0));if(0<$(a.target).closest('input[type\x3d"checkbox"]').length)b.closest("label").toggleClass("ativo"),q(b),a.stopPropagation();else if(b.is("li")){if("disabled"!=b.find("input").attr("disabled"))b.find("label").toggleClass("ativo"),b.find("input").attr("checked",function(){this.checked=!this.checked});else return;q(b)}var e="loadmore"==b.attr("id");g=e?g+1:1;g=b.hasClass("pagination")?
b.data("page"):g;a=f.data("query");var d=f.data("traveltype"),h=f.data("searchbycity"),t=f.data("searchfrom"),u=$("input#fromAmount").val(),v=$("input#toAmount").val(),w=c("monthsTravelReservation"),l=c("personQuantity"),m=c("stayingDays"),n=c("departureCities"),o=c("meals"),i=c("freeChildrenAge"),x=f.data("cityid");if(b.hasClass("srsort")){var k=$(".resultado-busca li:first-child"),p=k.parent();if(k.hasClass("open")){k.removeClass("open");if(j==b.data("sort")){p.find("li:nth-child(1)").nextAll().slideUp();
return}k.before(b);p.find("li:nth-child(1)").nextAll().slideUp();j=b.data("sort")}else{k.addClass("open");p.find("li:nth-child(1)").nextAll().slideDown();return}}$("article.deallist").addClass("opacity");if(null==d||""==$.trim(d))d="busca";if(null==a||""==$.trim(a))a="todos";$.get("/"+d+f.data("city-name")+"/"+a,{page:g,sort:j,fromAmount:u,toAmount:v,monthsTravelReservation:w,personQuantity:l,stayingDays:m,departureCities:n,meals:o,freeChildrenAge:i,searchByCity:h,searchFrom:t,cityId:x},function(a){var b=
$(".deallist").last(function(){return $(this).closest(".deallist")});-1==$("#loadmore",a).index()?$("#loadmore").hide():($("#loadmore").replaceWith($("#loadmore",a)),$("#loadmore").show());if(e)b.after($(".deallist",a)),s(b.next()),$("article.deallist").removeClass("opacity");else{var c=$(".deallist");1>b.index()?$("span#srquery").after($(".deallist",a)):b.after($(".deallist",a));c.remove();$(".totalHits").html($(".totalHits",a).html());for(var b=r(),c=r(a),d=0;d<b.length;d++){var f=$("#"+b[d]);-1==
c.indexOf(b[d])?(f.attr("disabled","disabled"),f.closest("li").addClass("off")):(f.removeAttr("disabled"),f.closest("li").removeClass("off"))}-1<$("#pagination").index()&&$("#pagination").html($("#pagination",a).html());$("article.deallist").removeClass("opacity");s($(".totalHits"))}})});$("li.showmore").on("click",function(a){$this=$(this);$this.siblings("li").show();$this.remove();a.preventDefault()});$(document).on("click","a.srdeal, img.srdeal",function(a){var b=$(this),e,d=$("#srquery");e=d.data("query");
var f=d.data("traveltype"),d=d.data("cityid"),g=$("input#fromAmount").val(),h=$("input#toAmount").val(),i=c("monthsTravelReservation"),j=c("personQuantity"),l=c("stayingDays"),m=c("departureCities"),n=c("meals"),o=c("freeChildrenAge");e="?fromAmount\x3d"+g+"\x26toAmount\x3d"+h+"\x26monthsTravelReservation\x3d"+i+"\x26personQuantity\x3d"+j+"\x26stayingDays\x3d"+l+"\x26departureCities\x3d"+m+"\x26meals\x3d"+n+"\x26travelType\x3d"+f+"\x26freeChildrenAge\x3d"+o+"\x26query\x3d"+e+"\x26cityId\x3d"+d;b=
b.is("a")?b.attr("href"):b.closest("a").attr("href");e=0<b.indexOf("?")?"\x26"+e.substring(1):e;a.preventDefault();document.location=b+e});$("#fromAmount, #toAmount").on("keydown",function(a){"13"==(a.keyCode?a.keyCode:a.which)&&$("#amountbtn").trigger("click")});$(document).on("ajaxComplete",function(){$(".split").each(function(){var a=$(this);a.text().length>a.data("textsize")&&a.text(function(b,c){return c.slice(0,a.data("textsize"))+"..."})})});$(".goto").on("click",function(){document.location=
$(this).find("a").attr("href")})});