var xt1=".dudi.com.br",xtLogDom=".ati-host.net/hit.xiti",xtpreview=!1,xtfirst=!1,xtcode="",xt46="1",xt50="1",xt48="",xt54=!1,xt58=!1,xtdocl=!1,xtud="undefined",xt2="1",xt3=3650,xtkwv="xtmc",xtkwp="xtnp",xtadch=[],xt4=[];xt4.sec="20";xt4.rss="20";xt4.epr="20";xt4.erec="20";xt4.adi="20";xt4.adc="20";xt4.al="20";xt4.es="20";xt4.ad="20";
var xtoid=[],xtnop=!0,xtkey=!1,xt49=null,xt5=30,xw=window,xd=document,xtg=navigator,xtv=null!=xw.xtczv?"43003-"+xw.xtczv:"43003",xt1=xw.xtdmc?";domain\x3d"+xw.xtdmc:""!=xt1?";domain\x3d"+xw.xt1:"",xt6=null!=xw.xtnv?xw.xtnv:xd,xt7=null!=xw.xtsdi?xw.xtsdi:null!=xw.xtsd?xw.xtsd+xtLogDom:("https:"==xd.location.protocol?"https://logws1306":"http://logw306")+xtLogDom,xt36=null!=xw.xtsts?xw.xtsts:0,xt37="";
if(xt54){var xturl="";try{xturl=xt6.location.href}catch(e){xturl=xw.location.href}xt37=(xt37=xtestr(xturl,/#.*/,1))?"\x26sta\x3d"+encodeURIComponent(xtclURL(xt37)):""}
var xt38=null!=xw.xtcustom?xtserial(xw.xtcustom):"",xt8=null!=xw.xtsite?xw.xtsite:0,xt9=null!=xw.xtn2?"\x26s2\x3d"+xw.xtn2:"",xt8b=(0==xt8?"":"s\x3d"+xt8)+(0==xt36?"":0==xt8?"sts\x3d"+xt36:"\x26sts\x3d"+xt36),xtp=null!=xw.xtpage?xw.xtpage:"",xt10=xw.xto_force?xw.xto_force.toLowerCase():null,xt11="redirect"==xt8?!0:!1,xtdi=xw.xtdi?"\x26di\x3d"+xw.xtdi:"",xt12=xw.xtidp?"\x26idpays\x3d"+xw.xtidp:"",xt13=xw.xtidprov?"\x26idprov\x3d"+xw.xtidprov:"",xtm=null!=xw.xtparam?xw.xtparam:"",xt46="undefined"!=
typeof xw.xtnopage&&"1"==xw.xtnopage?"0":xt46,xt50="undefined"!=typeof xw.xtergo&&"0"==xw.xtergo?"0":xt50,xtclzone="undefined"!=typeof xw.scriptOnClickZone&&"1"==xt50?xw.scriptOnClickZone:0,xt15=null!=xw.xt_orderid?xw.xt_orderid:"",xt17=null!=xw.xtidcart?xw.xtidcart:"",xt44=null!=xw.xtprod_load?"\x26pdtl\x3d"+xw.xtprod_load:"",xt47=""!=xw.xtcode?"\x26code\x3d"+xw.xtcode:"",xt60={i:[],u:[],d:[],l:[],e:[],p:[]},xtpre=!1,xtone=!0;
xw.addEventListener?xw.addEventListener("unload",function(){},!1):xw.attachEvent&&xw.attachEvent("onunload",function(){});xd.addEventListener?(xd.addEventListener("keydown",function(){xtkey=!0},!1),xd.addEventListener("keyup",function(){xtkey=!1},!1)):xd.attachEvent&&(xd.attachEvent("onkeydown",function(){xtkey=!0}),xd.attachEvent("onkeyup",function(){xtkey=!1}));
var xt18=xw.roimt&&0>xtm.indexOf("\x26roimt",0)?"\x26roimt\x3d"+xw.roimt:"",xtmc=0>xtm.indexOf("\x26mc\x3d",0)?xw.xtmc?"\x26mc\x3d"+xw.xtmc:xtf3(xtkwv)?"\x26mc\x3d"+xtf3(xtkwv):xtf3("xtmc")?"\x26mc\x3d"+xtf3("xtmc"):"":"",xtcr=xtf3("xtcr")?"\x26mcrg\x3d"+xtf3("xtcr"):"",xtac=xw.xtac&&0>xtm.indexOf("\x26ac\x3d",0)?"\x26ac\x3d"+xw.xtac:"",xtat=xw.xtat&&0>xtm.indexOf("\x26at\x3d",0)?"\x26at\x3d"+xw.xtat:"",xtan=xw.xtan&&0>xtm.indexOf("\x26an\x3d",0)?"\x26an\x3d"+xw.xtan:"",xtnp=0>xtm.indexOf("\x26np\x3d",
0)?xw.xtnp?"\x26np\x3d"+xw.xtnp:xtf3(xtkwp)?"\x26np\x3d"+xtf3(xtkwp):xtf3("xtnp")?"\x26np\x3d"+xtf3("xtnp"):"":"",xt19=null!=xw.xtprm&&0>xtm.indexOf("\x26x",0)?xw.xtprm:"",xtm=xtm+(xt18+xtmc+xtcr+xtac+(""!=xtan?xtan:xtat)+xtnp+xt19+xt37),xt20="";try{xt20=top.document.referrer}catch(e$$1){try{xt20=xt6.referrer}catch(e$$2){}}var xts=screen,xt21=new Date,xt22=xt21.getTime()/36E5;
function xtserial(a){var b=typeof a;if("object"!=b||null===a)return"string"==b&&(a=encodeURIComponent('"'+a+'"')),String(a);var f,c,d=[],g=a&&a.constructor==Array;for(f in a)c=a[f],b=typeof c,"string"==b?c=encodeURIComponent('"'+c+'"'):"object"==b&&null!==c&&(c=xtserial(c)),d.push((g?"":encodeURIComponent('"'+f+'":'))+String(c));return(g?"[":"{")+String(d)+(g?"]":"}")}function xtclURL(a){return a.replace(/%3C/g,"\x3c").replace(/%3E/g,"\x3e").replace(/[<>]/g,"")}
function xtf1(a,b){b=null!=b&&b!=xtud?b:"0";var f=RegExp("(?:^| )"+a+"\x3d([^;]+)").exec(xd.cookie)||null;f&&(f=xtclURL(f[1]),"1"!=b&&(f=unescape(f)));return f}function xt_addchain(a,b){xtvarch=b?b:"abmv";itemp=!xtadch[xtvarch]?0:xtadch[xtvarch];itemp++;xtm+="\x26"+xtvarch+""+itemp+"\x3d"+a;xtadch[xtvarch]=itemp}"function"==typeof xt_adch&&xt_adch();function wck(a,b,f,c,d){b=0==d?b:escape(b);xd.cookie=a+"\x3d"+b+";expires\x3d"+f.toGMTString()+";path\x3d/"+c}
function xtf3(a,b,f){try{var c=xt6.location.href}catch(d){c=xw.location.href}b=null==b||b==xtud?xtclURL(c.toLowerCase().replace(/%3d/g,"\x3d")):b;if(0<b.indexOf(a+"\x3d")){b=b.substr(1);a=b.substr(b.indexOf(a+"\x3d"));if(1!=f)try{a=decodeURIComponent(a)}catch(g){a=unescape(a)}if(b=a.match(/(\[[^\]]*\])/g))for(var c="",h=0,i=b.length;h<i;h++)c=b[h].substring(1,b[h].length-1),a=a.replace(c,encodeURIComponent(c));b=a.indexOf("#");c=a.search(/&.[^&]+=/gi);c=-1==c?-1==b?a.length:b:0<b&&b<c?b:c;return 1==
f?decodeURIComponent(a.substring(a.indexOf("\x3d")+1,c)):a.substring(a.indexOf("\x3d")+1,c).replace("\x26","%26")}return null}function xt_mvt(a,b,f,c,d){if(c)for(var g=1;g<c.length+1;g++)f+="\x26"+(d?d:"abmv")+g+"\x3d"+c[g-1];xtf4("","\x26p\x3d"+a+"\x26s2\x3d"+b+"\x26abmvc\x3d"+f+"\x26type\x3dmvt")}
function xt_med(a,b,f,c,d,g,h,i){xt_ajout="F"==a&&(null==c||c==xtud)?"":"M"==a?"\x26a\x3d"+c+"\x26m1\x3d"+d+"\x26m2\x3d"+g+"\x26m3\x3d"+h+"\x26m4\x3d"+i:"\x26clic\x3d"+c;xtf4(a,"\x26s2\x3d"+b+"\x26p\x3d"+f+xt_ajout,d,g)}
if(xtfirst=-1!=xtg.userAgent.indexOf("Safari")&&0>xtg.userAgent.indexOf("Chrome")||-1!=xtg.userAgent.indexOf("iPhone")||-1!=xtg.userAgent.indexOf("iPod")||-1!=xtg.userAgent.indexOf("iPad")||xtfirst||xw.xtidc){var xt40=xw.xtidc?xw.xtidc:xtf1("xtidc");if(null==xt40){var xt40=Math.floor(999999*Math.random()),xtane=xt21.getYear();100>xtane&&(xtane+=2E3);100<xtane&&2E3>xtane&&(xtane+=1900);var xt41=f_nb(xtane)+""+f_nb(xt21.getMonth())+""+f_nb(xt21.getDate())+""+f_nb(xt21.getHours())+""+f_nb(xt21.getMinutes())+
""+f_nb(xt21.getSeconds()),xt40=xt41+""+xt40}var xtdrc=new Date;xtdrc.setTime(xtdrc.getTime()+31536E7);wck("xtidc",xt40,xtdrc,xt1,1);xt42=xtf1("xtidc");xt40+=null==xt42||xt42!=xt40?"-NO":""}function xt_ad(a,b,f){xtf4("AT","\x26atc\x3d"+a+"\x26type\x3dAT\x26patc\x3d"+xtp+"\x26s2atc\x3d"+xw.xtn2,b,f)}function xt_adc(a,b,f,c){xtf4("AT","\x26atc\x3d"+b+"\x26type\x3dAT\x26patc\x3d"+xtp+"\x26s2atc\x3d"+xw.xtn2);return AT_click.do_navig(a,f,c?"_blank":null,!0)}
function xt_click(a,b,f,c,d,g,h){xt_ajout="F"==b&&(null==d||d==xtud)?"":"\x26clic\x3d"+d;xtf4(b,"\x26s2\x3d"+f+"\x26p\x3d"+c+xt_ajout);return AT_click.do_navig(a,g,h?"_blank":null,!0)}function xt_form(a,b,f,c,d,g){xt_ajout="F"==b&&(null==d||d==xtud)?"":"\x26clic\x3d"+d;xtf4(b,"\x26s2\x3d"+f+"\x26p\x3d"+c+xt_ajout);return AT_click.do_submit(a,!0,g)}
var AT_click={id:0,objs:[],elem:function(a,b,f,c,d,g){var h={};h.urlDest=d;h.type=a;h.n2=b;h.label=f;h.typeClick=c;h.target=g;h.submit=!1===d?!1:!0;return h},addListener:function(a,b,f){window.addEventListener?a.addEventListener(b,f,!1):window.attachEvent&&a.attachEvent("on"+b,f)},tag:function(a,b,f,c,d,g,h){if(a.setAttribute)this.addElem(a,b,f,c,d,g,h);else for(var i in a)a[i].setAttribute&&this.addElem(a[i],b,f,c,d,g,h)},addElem:function(a,b,f,c,d,g,h){this.id++;a.setAttribute("data-xtclickid",
this.id);this.objs[this.id]=this.elem(b,f,c,d,g,h);"FORM"!=a.nodeName?this.addListener(a,"click",this.on_click_submit):this.addListener(a,"submit",this.on_click_submit)},on_click_submit:function(a){try{var b=a.target||a.srcElement,f=b.getAttribute("data-xtclickid"),c={},d="",g=a.defaultPrevented,h=AT_click;f&&(c=h.objs[f],"AT"!=c.type?d+="\x26p\x3d"+c.label+("C"==c.type?"\x26clic\x3d"+c.typeClick:""):"AT"==c.type&&(d+="\x26type\x3dAT\x26atc\x3d"+c.label),xtf4(c.type,"\x26s2\x3d"+c.n2+d),g||(a.preventDefault(),
"FORM"!=b.nodeName?h.do_navig(b,c.urlDest,c.target):h.do_submit(b,null,c.submit)))}catch(i){}},do_navig:function(a,b,f,c){var d=null;if("A"!=a.nodeName)for(var g=a.parentNode;g;){if("A"==g.nodeName){d=g;break}g=g.parentNode}else d=a;if(d){if(d.target=f||a.target||"_self",d.href=b||a.href,!c||c&&!xtkey)if("_self"==d.target.toLowerCase()){if(setTimeout('self.location.href\x3d"'+d.href+'"',500),c)return!1}else if("_top"==d.target.toLowerCase()){if(setTimeout('top.location.href\x3d"'+d.href+'"',500),
c)return!1}else if("_parent"==d.target.toLowerCase()){if(setTimeout('parent.location.href\x3d"'+d.href+'"',500),c)return!1}else if("_blank"==d.target.toLowerCase()&&(setTimeout('(xw.open("'+d.href+'","_blank")).focus();',1),c))return!1}else b&&("_blank"==f?setTimeout('(xw.open("'+b+'","_blank")).focus();',500):setTimeout('self.location.href\x3d"'+b+'"',500));if(c)return xtkey=!1,!0},do_submit:function(a,b,f){if(f&&(setTimeout(function(){a.submit()},500),b&&f))return!1}};
function xt_rm(a,b,f,c,d,g,h,i,j,k,l,m,n,o){xtf4(a,"\x26p\x3d"+f+"\x26s2\x3d"+b+"\x26type\x3d"+a+"\x26a\x3d"+c+"\x26m5\x3d"+l+"\x26m6\x3d"+m+(null!=d&&"0"!=d?"\x26"+d:"")+(null!=h&&"pause"!=c&&"stop"!=c?"\x26m1\x3d"+h+"\x26"+i+"\x26m3\x3d"+j+"\x26m4\x3d"+k+"\x26m7\x3d"+n+"\x26m8\x3d"+o+"\x26prich\x3d"+xtp+"\x26s2rich\x3d"+xw.xtn2:"")+(null!=g&&"0"!=g&&null!=h?"\x26rfsh\x3d"+g:""));d=new Date;if(null!=g&&"0"!=g&&("play"==c||"play\x26buf\x3d1"==c||"refresh"==c)){xt60.p[a]&&18E5<d.getTime()-xt60.p[a]&&
(xt60.d[a]=0);if(("play"==c||"play\x26buf\x3d1"==c)&&!xt60.d[a])xt60.d[a]=d.getTime()/1E3,xt60.l[a]=parseInt(h),c=Math.floor(g),c=1500<c?1500:5>c?5:c,xt60.i[a]=c,xt60.u[a]=c,xt60.p[a]=!1;else if("refresh"==c&&("live"==m||!xt60.l[a]||300<xt60.l[a]&&2>100*xt60.i[a]/xt60.l[a]))c=xt60.p[a]?xt60.e[a]:d.getTime()/1E3-xt60.d[a],5>100*xt60.u[a]/(c+30)&&(xt60.u[a]=5*((c+30)/100)),xt60.p[a]&&(xt60.p[a]=!1,xt60.d[a]=d.getTime()/1E3-xt60.e[a]),xt60.e[a]=c;xtoid[a]=xw.setTimeout("xt_rm('"+a+"','"+b+"','"+f+"','refresh','0','"+
g+"',null,'"+i+"','"+j+"','"+k+"','"+l+"','"+m+"')",1E3*xt60.u[a])}else if(("pause"==c||"stop"==c)&&null!=xw.xtoid)xw.clearTimeout(xtoid[a]),"stop"==c?xt60.i[a]=0:xt60.p[a]=d.getTime()}
function xtf4(a,b,f,c){if((0==xtclzone||3==xtclzone||"C"!=a)&&"P"!=a){if(-1<b.indexOf("\x26ati\x3d")){var d=xtf3("ati",b,1)||"";1500<d.length&&(b=b.replace("\x26ati\x3d"+d,""),xt_ParseUrl3(Xt_id+xt8b+"\x26type\x3dAT"+(xtfirst?"\x26idclient\x3d"+xt40:""),"\x26ati\x3d"+d.replace(/&/g,"%26"),1,1,"\x26ati\x3d",","))}if(xtnop&&"0"==xt46&&"F"==a)Xt_param=Xt_param.replace("\x26p\x3d"+xtf3("p",Xt_param),""),Xt_param=Xt_param.replace("\x26s2\x3d"+xtf3("s2",Xt_param),""),window.navigator&&"preview"===window.navigator.loadPurpose&&
-1!=xtg.userAgent.indexOf("Safari")&&0>xtg.userAgent.indexOf("Chrome")?xtpreview&&xtLhit(Xt_param+b+"\x26pvw\x3d1"):"prerender"==xd.webkitVisibilityState?(xtpre=!0,Xt_param+=b,xd.addEventListener("webkitvisibilitychange",xtLhit,!1)):xtLhit(Xt_param+b),xtnop=!1;else{d=new Date;b=xt8b+b+"\x26hl\x3d"+d.getHours()+"x"+d.getMinutes()+"x"+d.getSeconds();if(4<=parseFloat(xtg.appVersion))try{b+="\x26r\x3d"+xts.width+"x"+xts.height+"x"+xts.pixelDepth+"x"+xts.colorDepth}catch(g){}xt_ParseUrl(Xt_id,b+(xtfirst?
"\x26idclient\x3d"+xt40:""),"","1")}}null!=f&&(f!=xtud&&"M"!=a)&&(""==c||null==c?xd.location=f:(xfen=window.open(f,"xfen",""),xfen.focus()))}function f_nb(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a}var xtidpg=f_nb(xt21.getHours())+""+f_nb(xt21.getMinutes())+""+f_nb(xt21.getSeconds())+""+xt_rd(7),xt23=0,xt16="",xt43=0;
function xt_addProduct(a,b,f,c,d,g){xt23++;xt16+="\x26pdt"+xt23+"\x3d";xt16+=a?a+"::":"";xt16+=b?b:"";xt16+=f?"\x26qte"+xt23+"\x3d"+f:"";xt16+=c?"\x26mt"+xt23+"\x3d"+c:"";xt16+=d?"\x26dsc"+xt23+"\x3d"+d:"";xt16+=g?"\x26pcode"+xt23+"\x3d"+g:""}function xt_rd(a){return Math.floor(Math.random()*Math.pow(10,a))}
function xt_addProduct_v2(a,b,f,c,d,g,h,i,j){xt23++;xt16+="\x26pdt"+xt23+"\x3d";xt16+=a?a+"::":"";xt16+=b?b:"";xt16+=f?"\x26qte"+xt23+"\x3d"+f:"";xt16+=c?"\x26mt"+xt23+"\x3d"+c:"";xt16+=d?"\x26mtht"+xt23+"\x3d"+d:"";xt16+=g?"\x26dsc"+xt23+"\x3d"+g:"";xt16+=h?"\x26dscht"+xt23+"\x3d"+h:"";xt16+=j?"\x26roimt"+xt23+"\x3d"+j:"";xt16+=i?"\x26pcode"+xt23+"\x3d"+i:""}function xt_addProduct_load(a,b,f){b&&(xt43++,xt44+=1==xt43?"\x26pdtl\x3d":"|",xt44+=a?a+"::":"",xt44+=b,xt44+=f?";"+f:"")}
"function"==typeof xt_cart?xt_cart():xt16="";
function xt_ParseUrl(a,b,f,c){var d=[];if(0<b.length){for(var g=1600-f.length,h=0,i=0,i="",j=0;b.length>g&&i!=b&&0==j;){var i=b,k="\x26pdt";0>=b.lastIndexOf(k,g)&&(0>=b.lastIndexOf("\x26",g)?j=1:k="\x26");1==j?d[h]=b.substring(0,1600)+"\x26mherr\x3d1":(d[h]=b.substring(0,b.lastIndexOf(k,g)),b=b.substring(b.lastIndexOf(k,g),b.length),h++,g=1600)}if(0==j&&(d[h]=b,""!=xt38))if(5+xt38.length+b.length<g)d[h]+="\x26stc\x3d"+xt38;else{h++;for(xt38="\x26stc\x3d"+xt38;xt38.length>g&&i!=xt38;)i=xt38,k=",",
5>=xt38.lastIndexOf(k,g)&&(j=1),1==j?d[h]=xt38.substring(0,1600)+"\x26mherr\x3d1":(d[h]=xt38.substring(0,xt38.lastIndexOf(k,g)),xt38="\x26stc\x3d"+xt38.substring(xt38.lastIndexOf(k,g),xt38.length),h++,g=1600);0==j&&(d[h]=xt38)}for(i=0;i<=h;i++)if(0<h&&(d[i]+="\x26mh\x3d"+(i+1)+"-"+(h+1)+"-"+xtidpg),d[i]=0<i?""!=xt15||""!=xt17?xt8b+"\x26cmd\x3d"+xt15+"\x26idcart\x3d"+xt17+d[i]:xt8b+d[i]:d[i]+f,"1"==c){var l=new Image;l.src=a+d[i];l.onload=function(){l.onload=null}}}}
function xt_ParseUrl3(a,b,f,c,d,g,h){h||(h=xtidpg.substring(0,6)+xt_rd(8));var i=new Image,j="\x26mh\x3d"+f+"-"+c+"-"+h;if(1500<b.length){for(var k=b.split(RegExp("["+g+"]","gi")),l="",j=k[0].length,m=0;1500>j&&m<k.length;)l+=k[m]+g,m<k.length-1&&(j+=k[m+1].length+1),m+=1;c=1==c?Math.ceil(b.length/1500):c;j="\x26mh\x3d"+f+"-"+c+"-"+h;if(""!=l){i.src=a+"\x26idp\x3d"+h+j+l;i.onload=function(){i.onload=null};b=d;for(l=m;l<k.length;l++)b+=k[l]+(l==k.length-1?"":g);xt_ParseUrl3(a,b,f+1,c,d,g,h)}else i.src=
a+"\x26idp\x3d"+h+j+b.substring(0,1500)+"\x26mherr\x3d1",i.onload=function(){i.onload=null}}else b.length>d.length&&(i.src=1==f?a+"\x26idp\x3d"+h+b:a+"\x26idp\x3d"+h+j+b,i.onload=function(){i.onload=null})}function xtestr(a,b,f){var c=null;try{c=a.match(b)[f-1]}catch(d){c=null}return c}
function xtLhit(a){if(!xtpre&&xtone||!xd.webkitHidden&&xtone)a?(xt_ParseUrl(Xt_id,("string"==typeof a?a:Xt_param)+(xtfirst?"\x26idclient\x3d"+xt40:""),"\x26ref\x3d"+Xt_r.replace(/&/g,"$"),"1"),xtone=!1):"1"==xt46&&(xt_ParseUrl(Xt_id,Xt_param+(xtfirst?"\x26idclient\x3d"+xt40:""),"\x26ref\x3d"+Xt_r.replace(/&/g,"$"),xt46),xtone=!1),!1==xtone&&(""!=xt44&&xt_ParseUrl3(Xt_id+xt8b+"\x26p\x3d"+xtp+(xtfirst?"\x26idclient\x3d"+xt40:"")+(xw.xt_pageID?"\x26pid\x3d"+xw.xt_pageID+"\x26pchap\x3d"+(xw.xt_chap||
"")+"\x26pidt\x3d"+(xw.xt_pageDate||""):"")+"\x26type\x3dPDT"+xthl,xt44,1,1,"\x26pdtl\x3d","|"),1500<xtati.length&&xt_ParseUrl3(Xt_id+xt8b+"\x26p\x3d"+xtp+"\x26s2\x3d"+xw.xtn2+"\x26type\x3dAT"+(xtfirst?"\x26idclient\x3d"+xt40:""),"\x26ati\x3d"+xtati.replace(/&/g,"%26"),1,1,"\x26ati\x3d",","),"undefined"!=typeof xtscript&&(a=document.createElement("script"),a.type="text/javascript",a.async=!0,a.src=xtscript,(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]||document.getElementsByTagName("script")[0].parentNode).insertBefore(a,
null)))}
if(0!=xt8||0!=xt36||xt11){if(""!=xt48){var xtvid=xtf1("xtvid");xtvid||(xt49=xtvid=xt21.getTime()+""+xt_rd(6));var xtexp=new Date;xtexp.setMinutes(xtexp.getMinutes()+30);wck("xtvid",xtvid,xtexp,"",1)}var xtpm="xtor",xtpmd="xtdate",xtpmc="xtocl",xtpan="xtan",xtpat="xtat",xtpant="xtant",xt24=xtf3("xtor"),xtdtgo=xtf3("xtdt"),xt25=xtf3("xtref"),xt26=xtf3("xtan"),xt55=xtf3("xtat"),xt27=xtf3("an",xtm),xt56=xtf3("at",xtm),xt28=xtf3("ac",xtm),cookie_xtpmc=xtf1(xtpmc),cookie_xtgo=xtf1("xtgo"),cookie_xtord=xtf1("xtord"),
cookie_xtvrn=xtf1("xtvrn"),xtocl=null!=cookie_xtpmc?cookie_xtpmc:"$",xtord="0"==cookie_xtgo?cookie_xtord:null,xtgord=null!=cookie_xtgo?cookie_xtgo:"0",xtvrn=null!=cookie_xtvrn?cookie_xtvrn:"$",xtgmt=xt21.getTime()/6E4,xtgo=null!=xtdtgo?30>xtgmt-xtdtgo&&0<=xtgmt-xtdtgo?"2":"1":xtgord,xtpgt="1"==xtgord?"\x26pgt\x3d"+cookie_xtord:"1"==xtgo&&null!=xt24?"\x26pgt\x3d"+xt24:"",xto=null!=xt10?xt10:null!=xt24&&"0"==xtgo?xt24:!xt11?xtord:null,xto=0>xtocl.indexOf("$"+xto+"$")||"$"==xtocl?xto:null,xtock="0"==
xtgo?xto:"2"==xtgord?cookie_xtord:"2"==xtgo?xt24:null;if(null!=xtock){tmpxto=xtock.substring(0,xtock.indexOf("-"));var xtdrm=xt4[tmpxto]}else xtdrm="1";if(null==xtdrm||xtdrm==xtud)xtdrm=xt4.ad;null==xt26&&!xt11&&(xt26=xtf1("xtanrd"));null==xt55&&!xt11&&(xt55=xtf1("xtatrd"));var xtanc=xtf1(xtpan),xtattc=xtf1(xtpat),xtanct=xtf1(xtpant),xtxp=new Date,xt29=new Date,xt30=new Date;xt11?xtxp.setTime(xtxp.getTime()+1E3*xt5):xtxp.setTime(xtxp.getTime()+864E5*xtdrm);xt30.setTime(xt30.getTime()+18E5);xt29.setTime(xt29.getTime()+
864E5*xt3);var xt31=null!=xt26?xt26.indexOf("-"):0,xt57=null!=xt55?xt55.indexOf("-"):0,xtan2=null!=xt27?"":null!=xt26&&0<xt31?"\x26ac\x3d"+xt26.substring(0,xt31)+"\x26ant\x3d0\x26an\x3d"+xt26.substring(xt31+1,xt26.length):null!=xtanc?"\x26anc\x3d"+xtanc+"\x26anct\x3d"+xtanct:"",xtat2=null!=xt56?"":null!=xt55&&0<xt57?"\x26ac\x3d"+xt55.substring(0,xt57)+"\x26ant\x3d0\x26at\x3d"+xt55.substring(xt57+1,xt55.length):null!=xtattc?"\x26attc\x3d"+xtattc+"\x26anct\x3d"+xtanct:"",xt32=0>xtvrn.indexOf("$"+xt8+
"$")?"\x26vrn\x3d1":"",xt35=null!=xtf3("xtatc")&&null==xtf3("atc",xtm)?"\x26atc\x3d"+xtf3("xtatc"):"";""!=xt32&&wck("xtvrn",141>xtvrn.length?xtvrn+xt8+"$":xtvrn.substring(0,141),xt29,xt1,0);xt32+=null==xto?"":"\x26xto\x3d"+xto;xt32+=(""!=xtan2?xtan2:xtat2)+xtpgt+xt35;null!=xt27?(wck(xtpan,xt28+"-"+xt27,xt29,xt1,1),wck(xtpant,"1",xt29,xt1,1)):null!=xt26&&"1"!=xtanct&&(wck(xtpan,xt26,xt29,xt1,1),wck(xtpant,"0",xt29,xt1,1));null!=xt56?(wck(xtpat,xt28+"-"+xt56,xt29,xt1,1),wck(xtpant,"1",xt29,xt1,1)):
null!=xt55&&"1"!=xtanct&&(wck(xtpat,xt55,xt29,xt1,1),wck(xtpant,"0",xt29,xt1,1));var xtor=xtf1(xtpm),xtor_duree=xtf1(xtpmd),xtdate2=null!=xtor_duree?new Date(xtor_duree):new Date,xt34=xtdate2.getTime()/36E5,xtecart=0<=Math.floor(xt22-xt34)?Math.floor(xt22-xt34):0,xt32=xt32+(null==xtor?"":"\x26xtor\x3d"+xtor+"\x26roinbh\x3d"+xtecart),xt33="",Xt_r=null!=xt25?xt25.replace(/[<>]/g,""):xtf1("xtref");null==Xt_r&&(Xt_r=xt20.replace(/[<>]/g,""));null!=Xt_r&&(Xt_r=Xt_r.substring(0,1E3));if(xt11)wck("xtgo",
xtgo,xtxp,xt1,1),null!=xt24&&wck("xtord",xt24,xtxp,xt1,1),null!=xt26&&wck("xtanrd",xt26,xtxp,xt1,1),null!=xt55&&wck("xtatrd",xt55,xtxp,xt1,1),""!=Xt_r&&wck("xtref",Xt_r.replace(/&/g,"$"),xtxp,xt1,0),null!=xw.xtloc&&(xt6.location=xw.xtloc);else{null!=xtock&&(0>xtocl.indexOf("$"+escape(xtock)+"$")||"$"==xtocl)&&wck(xtpmc,xtocl+xtock+"$",xt30,xt1,1);var xt33=xt33+(xtg.javaEnabled()?"\x26jv\x3d1":"\x26jv\x3d0"),xtnav=xtg.appName+" "+xtg.appVersion,xtIE=xtnav.indexOf("MSIE");if(0<=xtIE)var xtvers=parseInt(xtnav.substr(xtIE+
5)),xtIE=!0;else xtvers=parseFloat(xtg.appVersion),xtIE=!1;var xtnet=0<=xtnav.indexOf("Netscape"),xtmac=0<=xtnav.indexOf("Mac"),xtOP=0<=xtg.userAgent.indexOf("Opera");if(xtIE&&5<=xtvers&&!xtmac&&!xtOP&&!xt11){try{xd.body.addBehavior("#default#clientCaps")}catch(e$$15){}var xtconn="\x26cn\x3d"+xd.body.connectionType,xtconn=xtconn+("\x26ul\x3d"+xd.body.UserLanguage);try{xd.body.addBehavior("#default#homePage")}catch(e$$16){}var xthome="";try{xthome=xd.body.isHomePage(location.href)?"\x26hm\x3d1":"\x26hm\x3d0"}catch(e$$17){}var xtresr=
"\x26re\x3d"+xd.body.offsetWidth+"x"+xd.body.offsetHeight}else xthome=xtconn="",xtresr=5<=xtvers?"\x26re\x3d"+xw.innerWidth+"x"+xw.innerHeight:"";var xtlang=xtnet&&4<=xtvers||xtOP?"\x26lng\x3d"+xtg.language:xtIE&&4<=xtvers&&!xtOP?"\x26lng\x3d"+xtg.userLanguage:"";wck("xtord","",xt21,xt1,1);if(null!=xtock&&(null==xtor||"1"==xt2))wck(xtpm,xtock,xtxp,xt1,1),wck(xtpmd,xt21,xtxp,xt1,1);var xthl="\x26hl\x3d"+xt21.getHours()+"x"+xt21.getMinutes()+"x"+xt21.getSeconds(),xt45=xtdocl?"\x26docl\x3d"+encodeURIComponent(xt6.location.href.replace(/&/g,
"#ec#")):"",Xt_param=xt8b+xt9+"\x26p\x3d"+xtp+xthl+xtdi+xt12+xt13+xt32+xt45+xt47+xtm+xtconn+xthome+xtlang+"\x26vtag\x3d"+xtv+"\x26idp\x3d"+xtidpg,xtvalCZ=xtf1("xtvalCZ",1);if(null!=xtvalCZ){var Xt_param=Xt_param+xtvalCZ,xtdateo=new Date;xtdateo.setTime(xtdateo.getTime()-36E5);wck("xtvalCZ",xtvalCZ,xtdateo,xt1,1)}var Xt_id=xt7+"?";if(4<=xtvers)try{xt33+="\x26r\x3d"+xts.width+"x"+xts.height+"x"+xts.pixelDepth+"x"+xts.colorDepth}catch(e$$18){}var xtide=xtf1("xtide");if(null!=xtock)switch(tmpxto.toLowerCase()){case "erec":case "epr":case "es":var xtmpide=
null;try{var xtide_t=xtock.match(/(\[[^\]]*\])|([^\-]+)|(-)/g),xtide_c=0;for(elem in xtide_t)"-"==xtide_t[elem]&&xtide_c++,5==xtide_c&&"-"!=xtide_t[elem]&&(xtmpide=xtide_t[elem])}catch(e$$19){xtmpide=null}null!=xtmpide&&(xtide=xtmpide,wck("xtide",xtide,xt29,"",1))}var Xt_param=Xt_param+(xt33+xtresr+xt16+(null!=xtide?"\x26ide\x3d"+xtide:"")),Xt_i=Xt_id+Xt_param+"\x26ref\x3d"+Xt_r.replace(/&/g,"$");xt49&&(Xt_param+="\x26lnk\x3d"+xt48+"\x26vid\x3d"+xt49);var xtati=xtf3("ati",Xt_param,1)||"";1500<xtati.length&&
(Xt_param=Xt_param.replace("\x26ati\x3d"+xtati,""));window.navigator&&"preview"===window.navigator.loadPurpose&&-1!=xtg.userAgent.indexOf("Safari")&&0>xtg.userAgent.indexOf("Chrome")?xtpreview&&"1"==xt46&&xtLhit(Xt_param+"\x26pvw\x3d1"):"prerender"==xd.webkitVisibilityState?(xtpre=!0,xd.addEventListener("webkitvisibilitychange",xtLhit,!1)):xtLhit()}}
0<xtclzone&&"function"==typeof xtNodesload&&(xt58?xw.addEventListener?xw.addEventListener("load",xtNodesload,!1):xw.attachEvent&&xw.attachEvent("onload",xtNodesload):xtNodesload());